version: "3.7"
services:
  db-psql:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: peter.s@implemica.com
      PGADMIN_DEFAULT_PASSWORD: peter
    container_name: pg-admin
    ports:
      - "82:80"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgres: 
    name: "postgres-data"